[package]
name = "Coyote"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = "4.5.20"
colored = "2.1.0"
derive-new = "0.7.0"
diesel = "2.2.4"
rand = "0.8.5"
thiserror = "1.0.64"
